### ISSUE TITLE
Hovering over track thumbs causes system gpu usage to spike

### ISSUE THREAD

**Issue by michaelgosling** [SpinShare/client#37]
![image](https://user-images.githubusercontent.com/28716158/87693306-313d1d80-c763-11ea-8a9a-6004a32b9c95.png)
I have a Radeon RX 5500 XT 8GB
no integrated gpu, running my desktop at 3440x1440. SpinShare client is the only application that causes this GPU usage spike by the system. Not sure why this is happening, I have some knowledge of react but very little experience with electron and no experience with Vue. The hover animations also sorta snap/lag for me.

**Comment by jy1263** [comment]
Hmm, could you pls send a screenshot of the `Details` tab in task manager when this is happening?

**Comment by michaelgosling** [comment]
Certainly, though I'm not entirely sure what im looking for here. If you want to see a specific column or process just let me know.

![image](https://user-images.githubusercontent.com/28716158/87778340-6e57ed00-c801-11ea-8a07-21fd6ca325f4.png)

**Comment by AndreasWebdev** [comment]
It is very likely our transformations on hover. I'll try to optimize that in the next update.

**Comment by michaelgosling** [comment]
Oh, I don't know if it matters but I just thought to mention I scale my desktop (using windows built-in scaling option) by 125%. I know sometimes scaling can cause weird issues with web apps.

**Comment by AndreasWebdev** [comment]
The app is built on electron, but large css transformations can be Ressource heavy. There are some ways to optimize this so we'll check that out

**Comment by michaelgosling** [comment]
Yeah it seems to be okayish when I'm not running much else, so its not a deal breaker or anything. Thanks for the prompt responses!

**Comment by SpinShare** [comment]
This was added to our main project over at https://gitlab.seebeyond.dev/spinshare/client/-/issues/43
