### ISSUE TITLE
[Feature Request] Ability to filter by Difficulty

### ISSUE THREAD

**Issue by michaelgosling** [SpinShare/client#38]
Hey, its me again, creating more work 😛. It would be nice to filter by difficulty, especially since clicking `back` will return you to the first page of results. I forked to see if I could add it and PR but unfortunately without knowing what kind of queries the API is capable of its impossible for me to add.

**Comment by SpinShare** [comment]
Hey, this is already in our project outline for future updates, it however needs adjustments on the server side. Please check https://gitlab.seebeyond.dev/spinshare/client/ and https://gitlab.seebeyond.dev/spinshare/server/ for our active repos, as this repo is just a mirror for easy public access.
